eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: admin-service
          uri: lb://API-SERVICE
          predicates:
            - Path=/api-service/**
        - id: ui-route
          uri: ${UI_URI}
          predicates:
            - Path=/**
server:
  port: 8080
